name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install
      - name: Install Playwright Browsers
        run: IS_ACTION=true pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: AUTH_SECRET="cGn9LuifARJXNgukb6kMq8ObYsVeuJzVjqEj15/lEgA=" AUTH_TRUST_HOST=true NEXT_PUBLIC_API_BASE_URL=https://veinscrum-api.inedible.dev/api/v1 API_BASE_URL=https://veinscrum-api.inedible.dev/api/v1 IS_ACTION=true pnpm exec playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
